### ISSUE TITLE
use api  how to write  code running  exec

### ISSUE THREAD

**Issue by haiwan-xm** [Corsinvest/cv4pve-api-php#10]
hi  boss.
how to  write php code  running api   qm guest exec ..?

**Comment by franklupo** [comment]
Hi,

$client->getNodes()->get("pve1")->getQemu()->get(100)->getAgent()->getExec()->exec($command, $input_data)

Best regards

**Comment by haiwan-xm** [comment]
> Hi,
> 
> $client->getNodes()->get("pve1")->getQemu()->get(100)->getAgent()->getExec()->exec($command, $input_data)
> 
> Best regards

tks, boss. so if we use agent config  ip address 
we in promox shell set is   qm guest exec 122 ip addr add 192.168.0.2/24 brd 192.168.0.255 dev eth0
so how to  write php code  from api running this set ip address?
ths boss give me guide. and  happy weekend

**Comment by haiwan-xm** [comment]
> $client->getNodes()->get("pve1")->getQemu()->get(100)->getAgent()->getExec()->exec($command, $input_data)

hi, boss we write code  php    runing error.
you see
![image](https://user-images.githubusercontent.com/45061573/84012996-ed5c3900-a9aa-11ea-889b-d3db3b260a7f.png)

**Comment by franklupo** [comment]
Hi,
the official documentation https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/agent/exec not use encode.
With pvesh this command work?

```sh
pvesh create /nodes/{node}/qemu/{vmid}/agent/exec
```

best regards

**Comment by haiwan-xm** [comment]
> Hi,
> the official documentation [https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/agent/exec](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/%7Bnode%7D/qemu/%7Bvmid%7D/agent/exec) not use encode.
> With pvesh this command work?
> 
> ```shell
> pvesh create /nodes/{node}/qemu/{vmid}/agent/exec
> ```
> 
> best regards

qm guest exec <VMID> -- <Commad inside VM>
we just  don't know hot to use php running exec.

**Comment by haiwan-xm** [comment]
> Hi,
> the official documentation [https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/agent/exec](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/%7Bnode%7D/qemu/%7Bvmid%7D/agent/exec) not use encode.
> With pvesh this command work?
> 
> ```shell
> pvesh create /nodes/{node}/qemu/{vmid}/agent/exec
> ```
> 
> best regards

hi, boss. we just  try  use agent  config  host ip address.

**Comment by franklupo** [comment]
> > Hi,
> > the official documentation [https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/agent/exec](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/%7Bnode%7D/qemu/%7Bvmid%7D/agent/exec) not use encode.
> > With pvesh this command work?
> > ```shell
> > pvesh create /nodes/{node}/qemu/{vmid}/agent/exec
> > ```
> > 
> > 
> > best regards
> 
> qm guest exec --
> we just don't know hot to use php running exec.

Does it work in the shell manually?

**Comment by franklupo** [comment]
news?

**Comment by franklupo** [comment]
Hi,
escape data using htmlspecialchars

**Comment by haiwan-xm** [comment]
> Hi,
> escape data using htmlspecialchars

tks, boss., so have  give me  a demo code running    php exec  config ip addres  ?
tks

**Comment by franklupo** [comment]
```php
$input_data1=  htmlspecialchars($input_data)
$client->getNodes()->get("pve1")->getQemu()->get(100)->getAgent()->getExec()->exec($command, $input_data1)
```

**Comment by haiwan-xm** [comment]
> ```
> $input_data1=  htmlspecialchars($input_data)
> $client->getNodes()->get("pve1")->getQemu()->get(100)->getAgent()->getExec()->exec($command, $input_data1)
> ```

tks, boss, let me    test

**Comment by haiwan-xm** [comment]
and we have a new trouble.  how to use qemu agent config vm  ip address.
for example. centos.  if we use exec command set ip address , later reboot    config  loss.  we  want   let ip config  write eth config.
tks , wish give me guide.

**Comment by franklupo** [comment]
I have no idea.
I think the Proxmox VE forum can help you.

**Comment by haiwan-xm** [comment]
> I have no idea.
> I think the Proxmox VE forum can help you.

him let me  write all operating system   config  shell. later  call   shell running .

**Comment by franklupo** [comment]
I do not understand

**Comment by haiwan-xm** [comment]
> I do not understand

this depends on the distribution/OS you're running in the VM, since they have different implementations (networkmanager, systemd-networkd. /etc/network/interfaces, and so on..)

cloud-init can be used to configure networking for VMs though, which would work simpler..

otherwise you can try writing scripts for each distro to configure network, and call that script with arguments via `qm guest exec`

**Comment by franklupo** [comment]
You will have to make specific scripts for each OS.

**Comment by haiwan-xm** [comment]
> You will have to make specific scripts for each OS.

hi , boss 
this  exec($command, $input_data1)  how to  write.
have wish give me  guide?
eg: set ip address or   df  or  ifconfig

**Comment by franklupo** [comment]
you have to look at the guide of Proxmox VE
