### ISSUE TITLE
Remove VZ and create/remove CT

### ISSUE THREAD

**Issue by Toneq** [Corsinvest/cv4pve-api-php#14]
Hi!

I have a question, what is the structure of VM removal?
And the second question is the structure of the creation and removal of CT

Greetings,
Tobiasz

**Comment by franklupo** [comment]
Hi,


Creation CT
$client->getNodes()->get("pve1")->getLcx()->createVm()
https://github.com/Corsinvest/cv4pve-api-php/blob/5014a23d5519871f00fb45a599796916d567cc93/src/PveClient.php#L13011

Remove CT
$client->getNodes()->get("pve1")->getLcx()->get("100").ì->destoryVm()
https://github.com/Corsinvest/cv4pve-api-php/blob/5014a23d5519871f00fb45a599796916d567cc93/src/PveClient.php#L13289

Best regards
