### ISSUE TITLE
Call to undefined method Corsinvest\ProxmoxVE\Api\PVEClusterNextid::getResponse()

### ISSUE THREAD

**Issue by TheBadalaMaster** [Corsinvest/cv4pve-api-php#15]
Hello. I am feeling a little dumb with how to get responses from methods like Nextid or for example "shutdown"

(To shutdown a machine i ended up using the Base Cliente like so:

  $client->setResponseType('json');
    $result = $client->create('/nodes/qindev/qemu/105/status/shutdown')->getResponse()->data;
return $result;

Could i please get an example of this? Thanks :D

**Comment by TheBadalaMaster** [comment]
Also, this definitely wouldn't work but i am confused as to how to pass parameters in the function:

    $result = $client->create("/nodes/bad/qemu/102/clone/")->params(['newid' => 109,
                'bwlimit' => null,
                'description' => 'Bad',
                'format' => null,
                'full' => null,
                'name' => 'Bad',
                'pool' => null,
                'snapname' => null,
                'storage' => null,
                'target' => null]);

**Comment by franklupo** [comment]
Hi,

![image](https://user-images.githubusercontent.com/6276309/123819989-83d30380-d8fa-11eb-8031-4cfb1864bc77.png)

or 
$nodeId="node01";
$vmId=100;
$newid=102;
$client->getNodes()->get($nodeId)->getQemu()->get($vmId)->getClone()->cloneVm($newid)

If you are using an IDE it shows the method with parameters

best regards

**Comment by TheBadalaMaster** [comment]
Thanks for your answer!

The first question in the issue is understood. About the second, if i am going to clone a VM and i want to specify options (i took this array from your code) how would i pass it down? as a parameter to cloneVm?

['newid' => 109,
            'bwlimit' => null,
            'description' => 'Bad',
            'format' => null,
            'full' => null,
            'name' => 'Bad',
            'pool' => null,
            'snapname' => null,
            'storage' => null,
            'target' => null])

Thanks and sorry to bother!

**Comment by franklupo** [comment]
The clone accept parameter
https://github.com/Corsinvest/cv4pve-api-php/blob/5014a23d5519871f00fb45a599796916d567cc93/src/PveClient.php#L12036

**Comment by TheBadalaMaster** [comment]
Thanks so much! everything working when doing a full clone. Still got to figure out how to do a linked clone.  For future reference it ended up working like this:

    $result = $client->getNodes()->get("bog1")->getQemu()->get(101)->getClone()->cloneVm(106, 0, 'test', null, null, 'test', null, null, null, null)->getResponse()->data;
 print_r($result);

**Comment by TheBadalaMaster** [comment]
Sorry, last question. How can I increase the debug level from the api side so I can see what error I'm getting (your java api has this but this one doesn't.


Thanks for all your help :)

**Comment by franklupo** [comment]
https://github.com/Corsinvest/cv4pve-api-php/blob/5014a23d5519871f00fb45a599796916d567cc93/src/PveClientBase.php#L137
