### ISSUE TITLE
Error on Resize

### ISSUE THREAD

**Issue by Nevercold** [Corsinvest/cv4pve-api-php#17]
Hey,

I have some problems with resizing a hard disk.

e.g. 
$disk = 10;
$host_name = "server01"; (ServerName)
$service_id = "100"; (VM ID)

`$request = $proxmox->getNodes()->get($host_name)->getQemu()->get($service_id)->getResize()->resizeVm("scsi0", "+".$disk ."G");`
Resizing does not work with the shown command, the error message just says "null". everything else works, with the same data.

I also get this error (sometimes).

```
"TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in \/vendor\/corsinvest\/cv4pve-api-php\/src\/Result.php:156",
"Stack trace:",
"#0 \/vendor\/corsinvest\/cv4pve-api-php\/src\/Result.php(156): array_key_exists()",
"#1 \/vendor\/corsinvest\/cv4pve-api-php\/src\/Result.php(166): Corsinvest\\ProxmoxVE\\Api\\Result->responseInError()",
"#2 proxmoxController.php(161): Corsinvest\\ProxmoxVE\\Api\\Result->getError()",
"#3 ..."
```

161 = `if(!$request->isSuccessStatusCode()) return ...`

Please help.

**Comment by franklupo** [comment]
Hi,
I check the problem and update you.

Best regards

**Comment by Nevercold** [comment]
I've tested a bit, the error occurs after the VM is created or cloned. Adjust the configuration is still possible. 

The error does not occur if I do it afterwards. Strange.

**Comment by franklupo** [comment]
Ok,
from web interface work correctly?

**Comment by Nevercold** [comment]
yea.

**Comment by franklupo** [comment]
> yea.

???

**Comment by Nevercold** [comment]
Everything works perfectly from the web interface (pve-7.1)

**Comment by franklupo** [comment]
Ok, 
You can reporduce erorr from api?

**Comment by Nevercold** [comment]
> Ok, You can reporduce erorr from api?
What do you mean?

=> VM is cloned (task finished)
```
$clone = $proxmox->getNodes()->get($host_name)->getQemu()->get($template_id)->getClone()->cloneVm(
      (int) $service_id,
      full: true,
      name: $subdomain
);
```

=> VM disk is resized (error)
```
$disk = $disk."G";
sleep(5);
$request = $proxmox->getNodes()->get($host_name)->getQemu()->get($service_id)->getResize()->resizeVm("scsi0", $disk);
    
if(!$request->isSuccessStatusCode()) return array("success" => false, "error" => $request->getResponse(), "status_code" => $request->getStatusCode());
```

If I would do updateVmAsync() before resize, that would work too, only resize doesn't work.

**Comment by franklupo** [comment]
The same step in web Gui work correctly? 

Best reagards

**Comment by Nevercold** [comment]
Strange. Yesterday I tried it, everything went perfectly via the web interface...

Today I try it, comes a timeout error. So apparently Proxmox needs time after the clone.
Running Resize again then worked. Facepalm.

command '/usr/bin/qemu-img resize -f qcow2 /var/lib/vz/images/1004/vm-1004-disk-0.qcow2 3221225472' failed: got timeout (500)

**Comment by Nevercold** [comment]
I'm adding a longer sleep in a moment, and testing again.

**Comment by franklupo** [comment]
Thank you so much you are doing a great job improving this library

**Comment by Nevercold** [comment]
Error found. With a sleep of 20 seconds it works.

**Comment by franklupo** [comment]
I have updated the library. Can you test if ok?

Bets regards

**Comment by Nevercold** [comment]
Have already updated, it seems that everything works
