### ISSUE TITLE
API Token Example?

### ISSUE THREAD

**Issue by hall-of-code** [Corsinvest/cv4pve-api-php#23]
Hello, is there any example how to establish a connection via API-Token instead Username/Password?

- When I do setApiToken() i cant connect. 
(- When I use token instead of the users password in the login() method it also not working)

What I forgot?

```
$client = new PveClient($cluster_data->hostname, $cluster_data->port);
$client->setApiToken($cluster_data->token);
$client->getVersion();
```

Would be nice if there is any example provided how to connect via Token.

Best Regards
Theo

**Comment by franklupo** [comment]
good. You are welcome.
