### ISSUE TITLE
How to get next bigger vmID?

### ISSUE THREAD

**Issue by OfflinePing** [Corsinvest/cv4pve-api-php#25]
Hey,
I want to automatically deploy new containers. How do I auto Increment the vmID?

my code:
`$client->getNodes()->get('pve-claas')->getLxc()->createVm('debian-11-standard_11.7.1_amd64.tar.zst', '...AUTOINCREMENT-HERE');`

**Comment by franklupo** [comment]
$client->getCluster()->getNextId()
