### ISSUE TITLE
How to Set Timeout?

### ISSUE THREAD

**Issue by noxomix** [Corsinvest/cv4pve-api-php#29]
How can we set a Timeout for example when the Host is not reachable? Currently its blocking my Webserver somehow If i try to Connect to a Proxmox Node which is offline.

**Comment by franklupo** [comment]
Hi,
at this moment there is no option.
It will be possible in the future.

Best regards

**Comment by noxomix** [comment]
Yes ive added it into my fork, please let me know if i should change something/add something.
