### ISSUE TITLE
JSON vs. x-www-form-urlencoded for PUT/POST

### ISSUE THREAD

**Issue by lukasbruha** [Corsinvest/cv4pve-api-php#33]
Hi, 

thx for you lib. But I was wondering if json_encode($parameters) for PUT/POST methods is correct behavior since API doc, see https://pve.proxmox.com/wiki/Proxmox_VE_API#API_URL, specifies following:

Parameters can be passed using standard HTTP techniques:
- via the URL
- using x-www-form-urlencoded content-type for PUT and POST request.

As far as I can see, there is no JSON support for PUT/POST parameters. Currently, I am getting 501 Not Implemented when I want to call eg. POST /api2/json/nodes/NODE-01/qemu/103/status/stop via this library. But once I replace $data = json_encode($parameters) to eg. $data = http_build_query($parameters) in [executeAction()](https://github.com/Corsinvest/cv4pve-api-php/blob/master/src/PveClientBase.php#L380) and remove array_push for headers' Content-Type and Content-Length on lines that follows, server accepts it with 200 OK. 

I am sure this library is using by several devs, so maybe it is about my Proxmox configuration. But since there is no official support of JSON mentioned in Proxmox documentation, I would kindly ask you for any response to this issue.

Thx.

**Comment by franklupo** [comment]
Hi,
what parameters do you pass?
can you attach an example?

best reagrds

**Comment by lukasbruha** [comment]
Hi, no parameters. The issue is in Content-Type and json_encode (although it is empty). Seems Proxmox API rejects it in general because of these both. FYI I am using Proxmox VE 8.1.4.

**Comment by franklupo** [comment]
is the solution not to pass parameters if they aren't there?

**Comment by lukasbruha** [comment]
I am not sure since JSON as input is not officially supported according to documentation. If method was protected instead of private, I would overwrite it myself to avoid JSON for PUT/POST completely and pass query instead although I think JSON is more pretty and would be suitable when Proxmox responses are in JSON as well.

Question: when you developed this lib, JSON was working with Proxmox POST call as mentioned above? I was wondering why I am the only one having these issues. Can you test it yourself in your dev env with Proxmox?

**Comment by franklupo** [comment]
check the problem and I'll update you

**Comment by franklupo** [comment]
Yes, if you want create a pull request

**Comment by lukasbruha** [comment]
Done, see https://github.com/Corsinvest/cv4pve-api-php/pull/34. Please merge it once you have time.
