### ISSUE TITLE
Expose HTTP Headers for requests made with PveClientBase

### ISSUE THREAD

**Issue by sdiv877** [Corsinvest/cv4pve-api-php#36]
Hey there, thanks for the library, it's been great to use so far.

## Overview
This is more of a feature request than bug, but it appears that the Proxmox API returns errors in HTTP headers, rather than the JSON response body in some cases.

This happens in multiple endpoints, but one example can be seen in `/api2/json/nodes/{node}/qemu/{vmid}/clone` ([docs here](https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/clone)). Here's what the headers looks like:
```
HTTP/1.1 500 VM is locked (backup)
Cache-Control: max-age=0
Connection: close
Date: Thu, 25 Jul 2024 23:24:26 GMT
Pragma: no-cache
Server: pve-api-daemon/3.0
Content-Length: 13
Content-Type: application/json;charset=UTF-8
Expires: Thu, 25 Jul 2024 23:24:26 GMT
```

Since this error is in the header rather than body, it's not present in the following methods for the `Result` class:
* `getReasonPhrase()`
* `getResponse()`
* `getErrors()`

It would be useful if the raw headers were accessible by the user in these scenarios.

## Steps to Replicate
1. Create a VM template in PVE
2. SSH onto the node this template is on, and open the template config file at `/etc/pve/qemu-server/<VMID>.conf`
3. Add the line `lock: backup` to the bottom of the file, to manually lock the template
4. Try to clone the VM using the Proxmox API,  you should get an error message in the response headers rather than the body

## Solution
There are multiple ways to solve this, but one way could potentially be to add a new field to the `Result` class, which contains the contents of the raw headers. The headers can then be inspected by the user when they encounter an error, if they need to.

I believe the code would need to be added somewhere here: https://github.com/Corsinvest/cv4pve-api-php/blob/master/src/PveClientBase.php#L460

-----

Happy to create a PR for this feature. Thanks for reading.

**Comment by franklupo** [comment]
If you want to create a PR.

best regards

**Comment by sdiv877** [comment]
I've created  PR here: https://github.com/Corsinvest/cv4pve-api-php/pull/37

Could you please take a look when you have some time?
