### ISSUE TITLE
[Feature] Change function to accept array

### ISSUE THREAD

**Issue by franklupo** [Corsinvest/cv4pve-api-php#5]
Change function parameter accept array only parameter changed.

example

**From**

> updateVm($acpi = null, $agent = null, $args = null, $autostart = null, $balloon = null, $bios = null, $boot = null, $bootdisk = null, $cdrom = null, $cores = null, $cpu = null, $cpulimit = null, $cpuunits = null, $delete = null, $description = null, $digest = null, $force = null, $freeze = null, $hostpciN = null, $hotplug = null, $hugepages = null, $ideN = null, $keyboard = null, $kvm = null, $localtime = null, $lock = null, $machine = null, $memory = null, $migrate_downtime = null, $migrate_speed = null, $name = null, $netN = null, $numa = null, $numaN = null, $onboot = null, $ostype = null, $parallelN = null, $protection = null, $reboot = null, $revert = null, $sataN = null, $scsiN = null, $scsihw = null, $serialN = null, $shares = null, $skiplock = null, $smbios1 = null, $smp = null, $sockets = null, $startdate = null, $startup = null, $tablet = null, $tdf = null, $template = null, $unusedN = null, $usbN = null, $vcpus = null, $vga = null, $virtioN = null, $vmstatestorage = null, $watchdog = null)

**To**

> 
> $params = [
>   'acpi'        => ...,
>   'scsihw'       => ...,,
> ];
> 
> updateVm($params)

**Comment by balthild** [comment]
Hello, is this support now?

**Comment by franklupo** [comment]
no but I'm planning a new version.

Best regards

**Comment by Exellent1988** [comment]
if i try to use only one parameter, like in the updateVM funktion, they all endup in the acpi subarray...
