### ISSUE TITLE
Proxmox 6 support

### ISSUE THREAD

**Issue by ferdl9999** [Corsinvest/cv4pve-api-php#6]
Hello,

this api isn't working for me under proxmox 6. When will there be an update?

Thanks for your great work!

**Comment by franklupo** [comment]
Hi 
Where is the error?

Best regards

**Comment by ferdl9999** [comment]
Hey,
sorry, it was my mistake. I connected to the server without using the FQDN.
I set the debug level to 2 and saw the error message. On a proxmox 5 host it worked using a hostname which was not the FQDN, but on my new proxmox 6 host it isn't working.

I think proxmox changed something in the security settings. Thanks for your help!

**Comment by franklupo** [comment]
You are welcome. 
If you want a professional support look at https://www.corsinvest.it/cv4pve-tools/
