### ISSUE TITLE
about promox novnc

### ISSUE THREAD

**Issue by haiwan-xm** [Corsinvest/cv4pve-api-php#7]
Hi
we login in promox novnc  use  api  have trouble.
do you share  php  login novnc demo?
if we  use root account login   have safe trouble.

**Comment by franklupo** [comment]
Hi,
can you send me the example code?

Best regards

**Comment by franklupo** [comment]
News?
best regards

**Comment by haiwan-xm** [comment]
hi
tks  franklupo. you  very  good.
we have complete.
nearlly   study kvm-novnc  for  php
and  happy new  year.

**Comment by franklupo** [comment]
Ok
If you want send me sample to add a wiki

Best regards and happy new year

**Comment by haiwan-xm** [comment]
hi   do you share  promox  firewall   php api code me ?
tks  or  demo

**Comment by franklupo** [comment]
I do not understand

**Comment by haiwan-xm** [comment]
about  promox   firewal api

**Comment by franklupo** [comment]
Hi,
to access firewall information on 
- cluster 
- node
- vm / container innode
