### ISSUE TITLE
lxc IP? 

### ISSUE THREAD

**Issue by huglester** [Corsinvest/cv4pve-api-php#8]
$client->getNodes()->get("nodex")->getLxc()->Vmlist()

but this one does not have and IP address. Any way to get it? 

thanks

**Comment by franklupo** [comment]
Hi,
loop for any ct and read config

**Comment by huglester** [comment]
thanks.
so basically this:

$client->getNodes()->get("nodex")->getLxc()->get(1001)->getConfig()->getRest()->getResponse()
