### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by consigliere23** [Corsinvest/cv4pve-api-php#9]
`Message:     Class 'Corsinvest\ProxmoxVE\Api\PveClient' not found
`
What to do?

**Comment by franklupo** [comment]
How you use it?

**Comment by consigliere23** [comment]
Just simple example. Have here a 7.1 PHP version.

**Comment by consigliere23** [comment]
`$client = new Corsinvest\ProxmoxVE\Api\PveClient("xxxx.xyz");`
autoload is included, just gives this error :/

**Comment by franklupo** [comment]
Try with 7.0

**Comment by consigliere23** [comment]
Not possible at the moment. Any ideas, why it's not working?

**Comment by franklupo** [comment]
Hi,
i test and work for me.
This library require lib-curl

**Comment by consigliere23** [comment]
I have that library installed. Just check it, obviously there is some issue.

**Comment by franklupo** [comment]
News?
